### ISSUE TITLE
Информация о покупателе.

### ISSUE THREAD

**Issue by Eddie980** [tinkoff-mobile-tech/AcquiringSdkAndroid#183]
Есть вопрос о том как работает данный функционал. А именно передача данных по заказу и покупателя **orderOptions** и **customerOptions**.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/43817429/214064168-c24931c6-dbd7-4cf5-a1a3-07e301780b9c.png">
**additionalData** прекрасно передаёт нужные данные по заказу. А вот с передачей данных покупателя есть проблемы.
Согласно исходному коду вашего sdk есть данная возможность.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/43817429/214064798-589fddaf-2bc7-4143-91ec-4cfdf7877e1c.png">
**data** должна работать аналогичным образом, но почему-то не работает. И данные которые передаются через это поле где-то теряются.
Если посмотреть информацию о заказе после оплаты. Получаем следующую картину.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/43817429/214066803-0241b86f-f949-485c-9a5a-fd1c40c1ddb1.png">
**orderOptions** передали наш параметр через **additionalData** в информацию о заказе. А вот **customerOptions** в информацию о покупателе передал только явные поля **customerKey** и **email**, а всё что было в **data**, где-то потерял. Так же основываясь на таком примере:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/43817429/214068493-f88cbe9a-84d5-4745-aaf9-34d6ff2bc490.png">
Хотелось бы уточнить откуда могли взяться поля **ФИО покупателя** и **телефон**, если у **customerOptions** таких полей нет? Из чека по данному заказу, хотя если телефоном ещё можно понять, то откуда ФИО всё равно неизвестно? Или эти параметры как-то ещё можно настраивать/задавать? А какие ещё параметры там могут быть? Где об этом можно посмотреть информацию?

**Comment by jQwout** [comment]
Здравствуйте.
Сейчас это реализованотак , что параметр customerOptions.data , учитывается только при привязки карт, при оплате эта информация не учитывается .
Если требуются доработки на стороне asdk, уточните  пожалуйста -  какие ,и уточните их критичность для вас.

**Comment by Eddie980** [comment]
Ну как минимум было бы не плохо чтобы поле **data** учитывалось при оплате. Как максимум, чтобы можно было передавать конкретные параметры, которые бы отображались на экране списка транзакций с нормальными названиями, как у **ID покупателя** и **Электронная почта**, по которым работают фильтры, которые находятся на этом же экране.

**Comment by harcoPro** [comment]
Добрый день!
Напишите, пожалуйста, напишите ваши предложения по улучшению личного кабинета сюда: [acq_help@tinkoff.ru](mailto:acq_help@tinkoff.ru) там ваше предложение рассмотрят.
