### ISSUE TITLE
Оплата новой картой без привязки к пользователю.

### ISSUE THREAD

**Issue by Eddie980** [tinkoff-mobile-tech/AcquiringSdkAndroid#207]
Можно ли как-то добавить возможность при оплате картой, чтобы при передаче параметров в **PaymentOptions** , в информации о пользователе **customerOptions**, а именно **customerKey**, не происходило привязки карты к данному пользователю, в случае успешной оплаты. Флаг какой может в интерфейсе, или хотя бы в сдк дополнительный флаг? Потому что сейчас единственный способ избежать привязки, и не видеть ранее добавленных карт это не передавать данный параметр в информации о покупателе, но тогда и отследить потом транзакцию по данному пользователю не получится. 
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/43817429/219420834-708af723-7031-424e-8633-34b986c5208c.png">
Поле **ID покупателя** будет отсутствовать.
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/43817429/219421191-0e3dd44c-695c-402c-b6c6-c1429663c515.png">

**Comment by jQwout** [comment]
Здравствуйте, насколько я понимаю, этот вопрос можно решить через настройки терминала - не сохранять карту при успешной оплате. На самом деле. Команда ASDK не занимается личным кабинетом, и вопросы по работе с ним нужно адресовать на [acq_help@tinkoff.ru](mailto:acq_help@tinkoff.ru)
