### ISSUE TITLE
Версия 2.11 должна иметь minSdk =21, но при компиляции  возникает ошибка, что необходим minSdk =24

### ISSUE THREAD

**Issue by chim0380** [tinkoff-mobile-tech/AcquiringSdkAndroid#209]
По описанию в changelog и по коду  gradlle на github версия 2.11 должна иметь minSdk =21, но при фактическом использовании при компиляции возникает ошибка, что необходим minSdk =24

Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [ru.tinkoff.acquiring:ui:2.11] ...\.gradle\caches\transforms-3\c66a35b7054bd49e5fb2bb06ef8693b1\transformed\jetified-ui-2.11\AndroidManifest.xml as the library might be using APIs not available in 21

Хотелось бы понимать, доступно ли 2.11 с Яндекс Pay для minSdk =21

**Comment by jQwout** [comment]
Здравствуйте, 
для работы с Yandex.pay через asdk  вам необходимо установить minSdk = 24, на 21 версии яндекс работать не будет.(ограничение несет в себе само решение от яндекс) .
Более того, если вы только присматриваетесь к подключению библиотеки, я бы порекомендовал версию 2.12, так как там имеет поддержка самоподписных сертификатов минцифр и тинькофф банка из коробки. Это нужно,  что бы в случае отзыва сертификатов из-за санкций, пользователю не надо было устанавливать сертификаты вручную.

**Comment by chim0380** [comment]
Спасибо. Мы уже принимаем СПБ через AcquiringSdkAndroid. 
В случае отзыва сертификатов. СПБ тоже престанет работать или это касается только платежей банковских карт?

**Comment by jQwout** [comment]
Да, если текущий сертификат  у банка отзовут. Заблаговременно предупредить мы не сможем. Поэтому рекомендую планировать переход на версию 2.12, понимаю , что не хочется отказываться от процента пользователей( с andorid< 7),  но есть риски.
