### ISSUE TITLE
Сдвоенный текст ошибки не неверный cvv

### ISSUE THREAD

**Issue by chim0380** [tinkoff-mobile-tech/AcquiringSdkAndroid#210]
Если при оплате картой ввести неверный cvv , и вести верный 3DS, то текст ошибки сдвоенный:

**Попробуйте снова или свяжитесь с банком, выпустившим карту Попробуйте снова или свяжитесь с банком, выпустившим карту**

Ошибка извлекается следующим способом:
 
```
 Throwable throwble = (Throwable) data.getSerializableExtra(TinkoffAcquiring.EXTRA_ERROR);
 String message = throwble.getLocalizedMessage();
```

**Comment by jQwout** [comment]
Здравствуйте, подскажите, это тестовый или продовый терминал?

**Comment by chim0380** [comment]
Prodaction

**Comment by jQwout** [comment]
Здравствуйте, нашли старый баг с формированием кастомной ошибки,  скорее всего , фикс войдет в ближайший релиз.

**Comment by jQwout** [comment]
https://github.com/tinkoff-mobile-tech/AcquiringSdkAndroid/pull/222/files#diff-86852b7601840b6626041e663f6979eb9ee7f77d083effbf0e848057f8e1be7c

**Comment by jQwout** [comment]
@chim0380  скажите, вы пробовали воспроизвести ошибку на крайней версии?

**Comment by harcoPro** [comment]
Закрыто в связи с обрывом коммуникации.
