### ISSUE TITLE
Быстрые платежи FPS текст?

### ISSUE THREAD

**Issue by NetylkinOV** [tinkoff-mobile-tech/AcquiringSdkAndroid#211]
Привет. Подскажите, можно изменить текст на кнопке быстрых платежей. Сейчас он выглядит так "Оплатить через fps", что смущает пользователей, поскольку обычно везде указывают так "Оплатить через СПБ". Спасибо.

**Comment by jQwout** [comment]
Здравствуйте, я так полагаю , вы говорите про платежную шторку , судя по всему, вы используете кастомную локализацию, 
в базовой локализации используется следующее значение 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/37448471/223062478-f406ddaa-f9c7-447c-87ba-8967f87740a8.png">
Пожалуйста, проверьте настройки локализации, вызов примерно такой FeaturesOptions#localizationSource,

так же вы можете создать подобный файл локализации с любым требуемым значением, и подставить его.

**Comment by NetylkinOV** [comment]
Привет. Добавил в настройки localizationSource = AsdkSource(Language.RU)
и все стало нормально :) Спасибо.
