### ISSUE TITLE
Не работают запросы на добавление карты и оплату

### ISSUE THREAD

**Issue by kolesnikov-pasha** [tinkoff-mobile-tech/AcquiringSdkAndroid#217]
В ответ на запрос на добавление тестовой карты приходит ошибка "Неверный номер карты". 
Карта:
4300 0000 0000 0777
11/22
111

**Comment by jQwout** [comment]
Здравствуйте, подскажите пожалуйста , какой терминал вы используется( тест или прод),  а так же настройки терминала(no, 3ds, 3dshold)

**Comment by kolesnikov-pasha** [comment]
Терминал продовский
Настройки -- 3ds

**Comment by jQwout** [comment]
Попробуйте сделать привязку на настоящей карте, подозреваю , что тестовая карта для тестового контура может не жеваться продовским 3ds'ом

**Comment by kolesnikov-pasha** [comment]
С настоящей картой то же самое

**Comment by jQwout** [comment]
А подскажите, какая версия у вас?

**Comment by jQwout** [comment]
также подскажите, это ошибка на уровне ввода данных, или приходит с сервера, если второе - понадобится указать более подробные данные для поиска ошибок на беке.

**Comment by kolesnikov-pasha** [comment]
Версия SDK последняя, ошибка при использовании экрана готового. openAttachCard или что-то такое

**Comment by jQwout** [comment]
Подробностей все равно не хватает. 
Нужно проверить  стартовые параметры экрана 
`FeaturesOptions` ,а именно
`validateExpiryDate & emailRequired`

так же хочется узнать, было ли полноценное прохождение 3ds? на каком этапе именно получили ошибку?
Укажите какого банка карта была использована?

так же прошу проверить настройку `network_security_config.xml`

должно быть что то типо 
`
<network-security-config>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="@raw/acq_tinkoff_root_cert" />
            <certificates src="@raw/acq_ministry_of_digital_development_root_cert" />
        </trust-anchors>
        ....
        `

**Comment by jQwout** [comment]
Здравствуйте, скажите, данное решение вам помогло?

**Comment by harcoPro** [comment]
Запрос закрыт в связи с обрывом коммуникации.
